name: Update README

on:
  workflow_run:
    workflows: ["Run Auto Sign"]
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2

    - name: Update README
      run: |
        echo "- Auto Sign-in run successful on $(date)" >> README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add README.md
        git commit -m "Update README with successful run"
        git push
